[package]
name = "pipedream"
version = "0.1.0"
authors = ["Björn Löfroth <bjorn.lofroth@gmail.com>"]

[dependencies]
rocket = "0.4.2"
reqwest = "0.9"
itertools = "0.8"
regex = "1.0"
getopts = "0.2"
serde_urlencoded = "0.6"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.4"